# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



#That Hankerin' for some quinoa crusted kale crowns, or prusciutto packed portobelo pockets? Then ride that fixie for some HipsterBytes and wash it down with a PBR.
### Do you have the Hipster Hunger?


User.create(name: "Rachel Warbelow", email: "demo+rachel@jumpstartlab.com", password: "password")
User.create(name: "Jeff Casimir", email: "demo+jeff@jumpstartlab.com", username: "j3", password: "password")
User.create(name: "Jorge Talez", email: "demo+jorge@jumpstartlab.com", username: "novohispano", password: "password")
User.create(name: "Josh Cheek", email: "demo+josh@jumpstartlab.com", username: "josh", password: "password", role: 1)
User.create(name: "Admin Admin", email: "admin@example.com", username: "ADMIN", password: "password", role: 1)


Category.create(name: "Small Plates", description: "Itty bitty, but not too small plates of delicousness. Try not to use these plates as your new guages.")
Category.create(name: "Medium Plates", description: "Sharable, if you can bring yourself to...")
Category.create(name: "Large Plates", description: "Ginormous plates that will fill your hipster pie hole to the brim.")
Category.create(name: "Desert Plates", description: "Sweets, Treats but no Meats")
Category.create(name: "Hipster Drinks", description: "Craftsy Cocktails and Beer galore")

Item.create(title: "Give Me a Beat", description: "You will get one Beet", price: 20.25).categories << Category.find(1)
Item.create(title: "Bearded Prawns", description: "Panko crusted - Head On - Deep fried prawns.", price: 20.25).categories << Category.find(1)
Item.create(title: "Oil-Spill Calamari", description: "Served with spicy soy-sauce and squid ink -O- the day.", price: 20.25).categories << Category.find(1)
Item.create(title: "Egg-Plant Quinoa", description: "'Herb'- crusted eggplant, served with that special sauce", price: 20.25).categories << Category.find(1)
Item.create(title: "Stuffed Beanie", description: "One large, hat-sized, portabelo mushroom stuffed with hipster hummus and local bison-calf-cheese", price: 20.25).categories << Category.find(1)
Item.create(title: "Tatted Fingers", description: "Large, and in charge, plantains drizzled in style .", price: 20.25).categories << Category.find(1)
Item.create(title: "Protester-Pie", description: "These beef wellington is so deliscious you will protest for more.", price: 20.25).categories << Category.find(2)
Item.create(title: "Fixed Gear Fritters", description: "Not yo mammas fritters. Watch your mouth drop like she did when she saw your first tat.", price: 20.25).categories << Category.find(2)
Item.create(title: "Skinny Jean Spagetti", description: "Spagetti squash lightly dressed with extra-extra-virgin olive oil and baby-back balsamic.", price: 20.25).categories << Category.find(2)
Item.create(title: "PRB", description: "Wet your whistle with this special prize", price: 20.25).categories << Category.find(2)
Item.create(title: "Skeptic Steak", description: "You don't think you should... But you should. And will", price: 20.25).categories << Category.find(3)
Item.create(title: "The Questionable Quiche", description: "Eggs probably from my backyard made with spinach, greens and other vetable shit that makes this quiche THE quiche.", price:20.25).categories << Category.find(3)
Item.create(title: "Insta-Grahmcracker Crusted Vegan Bites", description: "Turnips crusted with sweet delicious ultra vegan grahmcrackers crumbs.", price:20.25).categories << Category.find(3)
Item.create(title: "", description: "Grass-fed all soy free range Breadstick", price: 20.25).categories << Category.find(4)
Item.create(title: "Vintage Venison Bites", description: "35 year old venison chuncked into ", price: 20.25).categories << Category.find(4)
Item.create(title: "Da Freshest Seaweed", description: "Local caught seaweed", price:20.25).categories << Category.find(4)
Item.create(title: "Pierced Pancakes", description: "Fluffy and pierced.", price: 20.25).categories << Category.find(4)
Item.create(title: "Played out Panini", description: "All you would expect from a panini made by grandma", price: 20.25).categories << Category.find(5)
Item.create(title: "Mixed Tape Macarroni", description: "Chef put some work on this one, put it on and check it out", price: 20.25).categories << Category.find(5)
Item.create(title: "Plaid Bass", description: "more hip than the striped bass", price:20.25).categories << Category.find(5)
Item.create(title: "Anti-Frack-Fries", description: "You think you were pissed with you heard the started a fracking stie in your old home town? Try running out of these fries.", price:20.25).categories << Category.find(5)
Item.create(title: "Turnt-Up Tiramasu", description: "So creamy, it'll turnt you up.", price:20.25).categories << Category.find(5)
Item.create(title: "Alternative Artichokes", description: "These grilled artichokes will make you emo", price: 20.25).categories << Category.find(5)
Item.create(title: "Grunge burger", description: "Greasy, oily and loud", price:20.25).categories << Category.find(5)


Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 1, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 1, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 1, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 1, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 2, quantity: 6)
Order.create(user_id: 2, subtotal: 500, status: 0).order_items.create(item_id: 2, quantity: 6)
Order.create(user_id: 2, subtotal: 500, status: 1).order_items.create(item_id: 2, quantity: 6)
Order.create(user_id: 2, subtotal: 500, status: 1).order_items.create(item_id: 2, quantity: 6)
Order.create(user_id: 2, subtotal: 500, status: 1).order_items.create(item_id: 3, quantity: 6)
Order.create(user_id: 2, subtotal: 500, status: 1).order_items.create(item_id: 3, quantity: 6)
Order.create(user_id: 2, subtotal: 500, status: 1).order_items.create(item_id: 3, quantity: 6)
Order.create(user_id: 2, subtotal: 500, status: 1).order_items.create(item_id: 3, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 4, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 4, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 2).order_items.create(item_id: 4, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 4, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 5, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 5, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 5, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 5, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 0).order_items.create(item_id: 6, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 6, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 6, quantity: 6)
Order.create(user_id: 4, subtotal: 500, status: 0).order_items.create(item_id: 6, quantity: 6)
Order.create(user_id: 4, subtotal: 500, status: 3).order_items.create(item_id: 7, quantity: 6)
Order.create(user_id: 4, subtotal: 500, status: 3).order_items.create(item_id: 7, quantity: 6)
Order.create(user_id: 4, subtotal: 500, status: 3).order_items.create(item_id: 7, quantity: 6)
Order.create(user_id: 4, subtotal: 500, status: 3).order_items.create(item_id: 7, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 3).order_items.create(item_id: 8, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 8, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 8, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 8, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 11, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 11, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 11, quantity: 6)
Order.create(user_id: 3, subtotal: 500, status: 2).order_items.create(item_id: 11, quantity: 6)
Order.create(user_id: 1, subtotal: 500, status: 0).order_items.create(item_id: 21, quantity: 6)
